import { createFileRoute, Link } from '@tanstack/react-router';
import { useCurriculum } from '../hooks/useCurriculum';

export const Route = createFileRoute('/curriculum/$curriculumId')({
  component: CurriculumDetailPage,
});

function CurriculumDetailPage() {
  const { curriculumId } = Route.useParams();
  const { data: curriculum, isLoading } = useCurriculum(curriculumId);

  if (isLoading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="animate-pulse">
          <div className="h-8 bg-gray-200 rounded w-1/3 mb-4"></div>
          <div className="h-4 bg-gray-200 rounded w-1/2 mb-8"></div>
        </div>
      </div>
    );
  }

  if (!curriculum) {
    return (
      <div className="container mx-auto px-4 py-8 text-center">
        <h2 className="text-2xl font-bold mb-2">Curriculum not found</h2>
        <Link to="/curriculum" className="text-blue-600 hover:underline">
          Back to curriculum list
        </Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <Link
          to="/curriculum"
          className="text-blue-600 hover:underline mb-4 inline-block"
        >
          ← Back to curriculum
        </Link>
        <h1 className="text-4xl font-bold mb-2">{curriculum.title}</h1>
        <p className="text-gray-600 text-lg">{curriculum.description}</p>
        <div className="flex gap-6 mt-4 text-sm">
          <div>
            <span className="text-gray-600">Status:</span>{' '}
            <span className="font-semibold capitalize">{curriculum.status}</span>
          </div>
          <div>
            <span className="text-gray-600">Week:</span>{' '}
            <span className="font-semibold">
              {curriculum.current_week}/{curriculum.duration_weeks}
            </span>
          </div>
          <div>
            <span className="text-gray-600">Modules:</span>{' '}
            <span className="font-semibold">{curriculum.modules.length}</span>
          </div>
          {curriculum.ai_model_used && (
            <div>
              <span className="text-gray-600">Generated by:</span>{' '}
              <span className="font-semibold">{curriculum.ai_model_used}</span>
            </div>
          )}
        </div>
      </div>

      {/* Modules */}
      <div className="space-y-6">
        <h2 className="text-2xl font-bold">Modules</h2>
        {curriculum.modules.map((module, idx) => (
          <div
            key={module.id}
            className="bg-white border border-gray-200 rounded-lg overflow-hidden"
          >
            <div className="bg-gradient-to-r from-gray-50 to-gray-100 px-6 py-4 border-b border-gray-200">
              <div className="flex justify-between items-start">
                <div>
                  <h3 className="text-xl font-semibold mb-1">
                    {idx + 1}. {module.title}
                  </h3>
                  <p className="text-gray-600 text-sm mb-2">{module.theme}</p>
                  <div className="flex gap-4 text-xs text-gray-500">
                    <span>Weeks {module.start_week}-{module.end_week}</span>
                    <span>•</span>
                    <span>{module.lesson_count} lessons</span>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-blue-600">
                    {Math.round(module.completion_percentage)}%
                  </div>
                  <div className="text-xs text-gray-500">complete</div>
                </div>
              </div>
            </div>

            <div className="p-6">
              <Link
                to="/modules/$moduleId"
                params={{ moduleId: module.id }}
                className="inline-block bg-blue-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700 transition"
              >
                View Lessons
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
