"""add_exercise_audio_fields

Revision ID: 1eabc1835448
Revises: 7545e0e9dc36
Create Date: 2025-12-13 23:11:34.720693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eabc1835448'
down_revision: Union[str, Sequence[str], None] = '7545e0e9dc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('curriculum_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('midi_file_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('audio_files_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('audio_generation_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('audio_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('curriculum_exercises', schema=None) as batch_op:
        batch_op.drop_column('audio_generated_at')
        batch_op.drop_column('audio_generation_status')
        batch_op.drop_column('audio_files_json')
        batch_op.drop_column('midi_file_path')
    # ### end Alembic commands ###
