"""add_gospel_piano_application_fields

Revision ID: 2b8b44072eaa
Revises: d0598504e64c
Create Date: 2025-12-14 01:05:35.608049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8b44072eaa'
down_revision: Union[str, Sequence[str], None] = 'd0598504e64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_exercises', sa.Column('application_type', sa.String(length=20), nullable=True))
    op.add_column('curriculum_exercises', sa.Column('variant_count', sa.Integer(), nullable=False, server_default='4'))
    op.add_column('curriculum_exercises', sa.Column('midi_files_json', sa.Text(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_exercises', 'midi_files_json')
    op.drop_column('curriculum_exercises', 'variant_count')
    op.drop_column('curriculum_exercises', 'application_type')
    # ### end Alembic commands ###
