"""add_model_usage_tracking

Revision ID: 7545e0e9dc36
Revises: d8f3c2a91b45
Create Date: 2025-12-13 22:57:35.144047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7545e0e9dc36'
down_revision: Union[str, Sequence[str], None] = 'd8f3c2a91b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create model_usage_logs table
    op.create_table('model_usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_usage_logs_created_at'), 'model_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_usage_logs_model'), 'model_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_model_usage_logs_task_type'), 'model_usage_logs', ['task_type'], unique=False)

    # SQLite-compatible batch operations for foreign keys
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_practice_sessions_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Add columns to snippets
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_review_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interval_days', sa.Float(), nullable=False, server_default='1.0'))
        batch_op.add_column(sa.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'))
        batch_op.add_column(sa.Column('repetition_count', sa.Integer(), nullable=False, server_default='0'))

    # Add user_id to songs with foreign key
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_songs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_songs_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Update user_skill_profiles index to unique
    with op.batch_alter_table('user_skill_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skill_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_user_skill_profiles_user_id'), ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert user_skill_profiles index
    with op.batch_alter_table('user_skill_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skill_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_user_skill_profiles_user_id'), ['user_id'], unique=False)

    # Remove user_id from songs
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_songs_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_songs_user_id'))
        batch_op.drop_column('user_id')

    # Remove SRS columns from snippets
    with op.batch_alter_table('snippets', schema=None) as batch_op:
        batch_op.drop_column('repetition_count')
        batch_op.drop_column('ease_factor')
        batch_op.drop_column('interval_days')
        batch_op.drop_column('last_reviewed_at')
        batch_op.drop_column('next_review_at')

    # Remove foreign key from practice_sessions
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_practice_sessions_user_id', type_='foreignkey')

    # Drop model_usage_logs table
    op.drop_index(op.f('ix_model_usage_logs_task_type'), table_name='model_usage_logs')
    op.drop_index(op.f('ix_model_usage_logs_model'), table_name='model_usage_logs')
    op.drop_index(op.f('ix_model_usage_logs_created_at'), table_name='model_usage_logs')
    op.drop_table('model_usage_logs')
    # ### end Alembic commands ###
