"""Add User model and foreign keys

Revision ID: 7787f7a3a199
Revises: 8948c5427069
Create Date: 2025-12-13 09:41:48.673179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7787f7a3a199'
down_revision: Union[str, Sequence[str], None] = '8948c5427069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('practice_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'practice_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('snippets', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    op.add_column('snippets', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('snippets', sa.Column('interval_days', sa.Float(), nullable=False))
    op.add_column('snippets', sa.Column('ease_factor', sa.Float(), nullable=False))
    op.add_column('snippets', sa.Column('repetition_count', sa.Integer(), nullable=False))
    op.add_column('songs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_songs_user_id'), 'songs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'songs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_index(op.f('ix_songs_user_id'), table_name='songs')
    op.drop_column('songs', 'user_id')
    op.drop_column('snippets', 'repetition_count')
    op.drop_column('snippets', 'ease_factor')
    op.drop_column('snippets', 'interval_days')
    op.drop_column('snippets', 'last_reviewed_at')
    op.drop_column('snippets', 'next_review_at')
    op.drop_constraint(None, 'practice_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_column('practice_sessions', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
