"""add_tutorial_and_adaptation_fields

Revision ID: d0598504e64c
Revises: 1eabc1835448
Create Date: 2025-12-13 23:17:41.031220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0598504e64c'
down_revision: Union[str, Sequence[str], None] = '1eabc1835448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adaptation_history_json', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('last_adapted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('curriculum_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorial_content_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('tutorial_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('curriculum_lessons', schema=None) as batch_op:
        batch_op.drop_column('tutorial_generated_at')
        batch_op.drop_column('tutorial_content_json')

    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.drop_column('last_adapted_at')
        batch_op.drop_column('adaptation_history_json')
    # ### end Alembic commands ###
