"""Add exercise library tables only

Revision ID: fef0d9cc5b77
Revises: 0d47ee24b935
Create Date: 2025-12-16 22:28:13.565547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef0d9cc5b77'
down_revision: Union[str, Sequence[str], None] = '0d47ee24b935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_library',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_weeks', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('ai_provider', sa.String(length=100), nullable=True),
    sa.Column('times_accessed', sa.Integer(), nullable=False),
    sa.Column('avg_completion_rate', sa.Float(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('prerequisites_json', sa.Text(), nullable=True),
    sa.Column('learning_objectives_json', sa.Text(), nullable=True),
    sa.Column('modules_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_library_created_at'), 'curriculum_library', ['created_at'], unique=False)
    op.create_table('exercise_library',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('curriculum_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('midi_prompt', sa.Text(), nullable=True),
    sa.Column('midi_file_path', sa.String(length=500), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.Column('time_signature', sa.String(length=20), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('times_accessed', sa.Integer(), nullable=False),
    sa.Column('avg_completion_time', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_library_created_at'), 'exercise_library', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercise_library_curriculum_id'), 'exercise_library', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_exercise_library_difficulty'), 'exercise_library', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercise_library_exercise_type'), 'exercise_library', ['exercise_type'], unique=False)
    op.create_table('user_exercise_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=255), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('total_practice_time_seconds', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('quality_ratings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_index(op.f('ix_user_exercise_progress_exercise_id'), 'user_exercise_progress', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_progress_next_review'), 'user_exercise_progress', ['next_review'], unique=False)
    op.create_index(op.f('ix_user_exercise_progress_user_id'), 'user_exercise_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_exercise_progress_user_id'), table_name='user_exercise_progress')
    op.drop_index(op.f('ix_user_exercise_progress_next_review'), table_name='user_exercise_progress')
    op.drop_index(op.f('ix_user_exercise_progress_exercise_id'), table_name='user_exercise_progress')
    op.drop_table('user_exercise_progress')
    op.drop_index(op.f('ix_exercise_library_exercise_type'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_difficulty'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_curriculum_id'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_created_at'), table_name='exercise_library')
    op.drop_table('exercise_library')
    op.drop_index(op.f('ix_curriculum_library_created_at'), table_name='curriculum_library')
    op.drop_table('curriculum_library')
    # ### end Alembic commands ###
