/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoryIndexRouteImport } from './routes/theory/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as LibrarySongIdRouteImport } from './routes/library/$songId'
import { Route as LibrarySongIdPracticeRouteImport } from './routes/library/$songId/practice'
import { Route as LibrarySongIdAnalyzeRouteImport } from './routes/library/$songId/analyze'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryIndexRoute = TheoryIndexRouteImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySongIdRoute = LibrarySongIdRouteImport.update({
  id: '/library/$songId',
  path: '/library/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySongIdPracticeRoute = LibrarySongIdPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => LibrarySongIdRoute,
} as any)
const LibrarySongIdAnalyzeRoute = LibrarySongIdAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => LibrarySongIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/discover': typeof DiscoverIndexRoute
  '/library': typeof LibraryIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/discover': typeof DiscoverIndexRoute
  '/library': typeof LibraryIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/discover/': typeof DiscoverIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/settings'
    | '/upload'
    | '/library/$songId'
    | '/discover'
    | '/library'
    | '/practice'
    | '/theory'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/settings'
    | '/upload'
    | '/library/$songId'
    | '/discover'
    | '/library'
    | '/practice'
    | '/theory'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/settings'
    | '/upload'
    | '/library/$songId'
    | '/discover/'
    | '/library/'
    | '/practice/'
    | '/theory/'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  LibrarySongIdRoute: typeof LibrarySongIdRouteWithChildren
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  TheoryIndexRoute: typeof TheoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/': {
      id: '/theory/'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$songId': {
      id: '/library/$songId'
      path: '/library/$songId'
      fullPath: '/library/$songId'
      preLoaderRoute: typeof LibrarySongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$songId/practice': {
      id: '/library/$songId/practice'
      path: '/practice'
      fullPath: '/library/$songId/practice'
      preLoaderRoute: typeof LibrarySongIdPracticeRouteImport
      parentRoute: typeof LibrarySongIdRoute
    }
    '/library/$songId/analyze': {
      id: '/library/$songId/analyze'
      path: '/analyze'
      fullPath: '/library/$songId/analyze'
      preLoaderRoute: typeof LibrarySongIdAnalyzeRouteImport
      parentRoute: typeof LibrarySongIdRoute
    }
  }
}

interface LibrarySongIdRouteChildren {
  LibrarySongIdAnalyzeRoute: typeof LibrarySongIdAnalyzeRoute
  LibrarySongIdPracticeRoute: typeof LibrarySongIdPracticeRoute
}

const LibrarySongIdRouteChildren: LibrarySongIdRouteChildren = {
  LibrarySongIdAnalyzeRoute: LibrarySongIdAnalyzeRoute,
  LibrarySongIdPracticeRoute: LibrarySongIdPracticeRoute,
}

const LibrarySongIdRouteWithChildren = LibrarySongIdRoute._addFileChildren(
  LibrarySongIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  LibrarySongIdRoute: LibrarySongIdRouteWithChildren,
  DiscoverIndexRoute: DiscoverIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  TheoryIndexRoute: TheoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
