/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestAudioRouteImport } from './routes/test-audio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoryIndexRouteImport } from './routes/theory/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as GeneratorIndexRouteImport } from './routes/generator/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as TheoryLabRouteImport } from './routes/theory/lab'
import { Route as PracticeHandsRouteImport } from './routes/practice/hands'
import { Route as LibrarySongIdRouteImport } from './routes/library/$songId'
import { Route as GenresTheoryRouteImport } from './routes/genres/theory'
import { Route as CurriculumPerformanceRouteImport } from './routes/curriculum/performance'
import { Route as CurriculumDailyRouteImport } from './routes/curriculum/daily'
import { Route as CurriculumAssessmentRouteImport } from './routes/curriculum/assessment'
import { Route as LibraryCollectionsIndexRouteImport } from './routes/library/collections/index'
import { Route as LibrarySongIdPracticeRouteImport } from './routes/library/$songId/practice'
import { Route as LibrarySongIdAnalyzeRouteImport } from './routes/library/$songId/analyze'
import { Route as CurriculumLessonsLessonIdRouteImport } from './routes/curriculum/lessons/$lessonId'

const TestAudioRoute = TestAudioRouteImport.update({
  id: '/test-audio',
  path: '/test-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryIndexRoute = TheoryIndexRouteImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorIndexRoute = GeneratorIndexRouteImport.update({
  id: '/generator/',
  path: '/generator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryLabRoute = TheoryLabRouteImport.update({
  id: '/theory/lab',
  path: '/theory/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeHandsRoute = PracticeHandsRouteImport.update({
  id: '/practice/hands',
  path: '/practice/hands',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySongIdRoute = LibrarySongIdRouteImport.update({
  id: '/library/$songId',
  path: '/library/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresTheoryRoute = GenresTheoryRouteImport.update({
  id: '/genres/theory',
  path: '/genres/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumPerformanceRoute = CurriculumPerformanceRouteImport.update({
  id: '/curriculum/performance',
  path: '/curriculum/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumDailyRoute = CurriculumDailyRouteImport.update({
  id: '/curriculum/daily',
  path: '/curriculum/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumAssessmentRoute = CurriculumAssessmentRouteImport.update({
  id: '/curriculum/assessment',
  path: '/curriculum/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCollectionsIndexRoute = LibraryCollectionsIndexRouteImport.update({
  id: '/library/collections/',
  path: '/library/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySongIdPracticeRoute = LibrarySongIdPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => LibrarySongIdRoute,
} as any)
const LibrarySongIdAnalyzeRoute = LibrarySongIdAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => LibrarySongIdRoute,
} as any)
const CurriculumLessonsLessonIdRoute =
  CurriculumLessonsLessonIdRouteImport.update({
    id: '/curriculum/lessons/$lessonId',
    path: '/curriculum/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-audio': typeof TestAudioRoute
  '/curriculum/assessment': typeof CurriculumAssessmentRoute
  '/curriculum/daily': typeof CurriculumDailyRoute
  '/curriculum/performance': typeof CurriculumPerformanceRoute
  '/genres/theory': typeof GenresTheoryRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/practice/hands': typeof PracticeHandsRoute
  '/theory/lab': typeof TheoryLabRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/generator': typeof GeneratorIndexRoute
  '/library': typeof LibraryIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/curriculum/lessons/$lessonId': typeof CurriculumLessonsLessonIdRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
  '/library/collections': typeof LibraryCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-audio': typeof TestAudioRoute
  '/curriculum/assessment': typeof CurriculumAssessmentRoute
  '/curriculum/daily': typeof CurriculumDailyRoute
  '/curriculum/performance': typeof CurriculumPerformanceRoute
  '/genres/theory': typeof GenresTheoryRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/practice/hands': typeof PracticeHandsRoute
  '/theory/lab': typeof TheoryLabRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/generator': typeof GeneratorIndexRoute
  '/library': typeof LibraryIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/curriculum/lessons/$lessonId': typeof CurriculumLessonsLessonIdRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
  '/library/collections': typeof LibraryCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/test-audio': typeof TestAudioRoute
  '/curriculum/assessment': typeof CurriculumAssessmentRoute
  '/curriculum/daily': typeof CurriculumDailyRoute
  '/curriculum/performance': typeof CurriculumPerformanceRoute
  '/genres/theory': typeof GenresTheoryRoute
  '/library/$songId': typeof LibrarySongIdRouteWithChildren
  '/practice/hands': typeof PracticeHandsRoute
  '/theory/lab': typeof TheoryLabRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/generator/': typeof GeneratorIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/curriculum/lessons/$lessonId': typeof CurriculumLessonsLessonIdRoute
  '/library/$songId/analyze': typeof LibrarySongIdAnalyzeRoute
  '/library/$songId/practice': typeof LibrarySongIdPracticeRoute
  '/library/collections/': typeof LibraryCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/test-audio'
    | '/curriculum/assessment'
    | '/curriculum/daily'
    | '/curriculum/performance'
    | '/genres/theory'
    | '/library/$songId'
    | '/practice/hands'
    | '/theory/lab'
    | '/curriculum'
    | '/discover'
    | '/generator'
    | '/library'
    | '/practice'
    | '/theory'
    | '/curriculum/lessons/$lessonId'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
    | '/library/collections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/test-audio'
    | '/curriculum/assessment'
    | '/curriculum/daily'
    | '/curriculum/performance'
    | '/genres/theory'
    | '/library/$songId'
    | '/practice/hands'
    | '/theory/lab'
    | '/curriculum'
    | '/discover'
    | '/generator'
    | '/library'
    | '/practice'
    | '/theory'
    | '/curriculum/lessons/$lessonId'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
    | '/library/collections'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/test-audio'
    | '/curriculum/assessment'
    | '/curriculum/daily'
    | '/curriculum/performance'
    | '/genres/theory'
    | '/library/$songId'
    | '/practice/hands'
    | '/theory/lab'
    | '/curriculum/'
    | '/discover/'
    | '/generator/'
    | '/library/'
    | '/practice/'
    | '/theory/'
    | '/curriculum/lessons/$lessonId'
    | '/library/$songId/analyze'
    | '/library/$songId/practice'
    | '/library/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TestAudioRoute: typeof TestAudioRoute
  CurriculumAssessmentRoute: typeof CurriculumAssessmentRoute
  CurriculumDailyRoute: typeof CurriculumDailyRoute
  CurriculumPerformanceRoute: typeof CurriculumPerformanceRoute
  GenresTheoryRoute: typeof GenresTheoryRoute
  LibrarySongIdRoute: typeof LibrarySongIdRouteWithChildren
  PracticeHandsRoute: typeof PracticeHandsRoute
  TheoryLabRoute: typeof TheoryLabRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  GeneratorIndexRoute: typeof GeneratorIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  TheoryIndexRoute: typeof TheoryIndexRoute
  CurriculumLessonsLessonIdRoute: typeof CurriculumLessonsLessonIdRoute
  LibraryCollectionsIndexRoute: typeof LibraryCollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-audio': {
      id: '/test-audio'
      path: '/test-audio'
      fullPath: '/test-audio'
      preLoaderRoute: typeof TestAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/': {
      id: '/theory/'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator/': {
      id: '/generator/'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/lab': {
      id: '/theory/lab'
      path: '/theory/lab'
      fullPath: '/theory/lab'
      preLoaderRoute: typeof TheoryLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/hands': {
      id: '/practice/hands'
      path: '/practice/hands'
      fullPath: '/practice/hands'
      preLoaderRoute: typeof PracticeHandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$songId': {
      id: '/library/$songId'
      path: '/library/$songId'
      fullPath: '/library/$songId'
      preLoaderRoute: typeof LibrarySongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/theory': {
      id: '/genres/theory'
      path: '/genres/theory'
      fullPath: '/genres/theory'
      preLoaderRoute: typeof GenresTheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/performance': {
      id: '/curriculum/performance'
      path: '/curriculum/performance'
      fullPath: '/curriculum/performance'
      preLoaderRoute: typeof CurriculumPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/daily': {
      id: '/curriculum/daily'
      path: '/curriculum/daily'
      fullPath: '/curriculum/daily'
      preLoaderRoute: typeof CurriculumDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/assessment': {
      id: '/curriculum/assessment'
      path: '/curriculum/assessment'
      fullPath: '/curriculum/assessment'
      preLoaderRoute: typeof CurriculumAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/collections/': {
      id: '/library/collections/'
      path: '/library/collections'
      fullPath: '/library/collections'
      preLoaderRoute: typeof LibraryCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$songId/practice': {
      id: '/library/$songId/practice'
      path: '/practice'
      fullPath: '/library/$songId/practice'
      preLoaderRoute: typeof LibrarySongIdPracticeRouteImport
      parentRoute: typeof LibrarySongIdRoute
    }
    '/library/$songId/analyze': {
      id: '/library/$songId/analyze'
      path: '/analyze'
      fullPath: '/library/$songId/analyze'
      preLoaderRoute: typeof LibrarySongIdAnalyzeRouteImport
      parentRoute: typeof LibrarySongIdRoute
    }
    '/curriculum/lessons/$lessonId': {
      id: '/curriculum/lessons/$lessonId'
      path: '/curriculum/lessons/$lessonId'
      fullPath: '/curriculum/lessons/$lessonId'
      preLoaderRoute: typeof CurriculumLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibrarySongIdRouteChildren {
  LibrarySongIdAnalyzeRoute: typeof LibrarySongIdAnalyzeRoute
  LibrarySongIdPracticeRoute: typeof LibrarySongIdPracticeRoute
}

const LibrarySongIdRouteChildren: LibrarySongIdRouteChildren = {
  LibrarySongIdAnalyzeRoute: LibrarySongIdAnalyzeRoute,
  LibrarySongIdPracticeRoute: LibrarySongIdPracticeRoute,
}

const LibrarySongIdRouteWithChildren = LibrarySongIdRoute._addFileChildren(
  LibrarySongIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TestAudioRoute: TestAudioRoute,
  CurriculumAssessmentRoute: CurriculumAssessmentRoute,
  CurriculumDailyRoute: CurriculumDailyRoute,
  CurriculumPerformanceRoute: CurriculumPerformanceRoute,
  GenresTheoryRoute: GenresTheoryRoute,
  LibrarySongIdRoute: LibrarySongIdRouteWithChildren,
  PracticeHandsRoute: PracticeHandsRoute,
  TheoryLabRoute: TheoryLabRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  GeneratorIndexRoute: GeneratorIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  TheoryIndexRoute: TheoryIndexRoute,
  CurriculumLessonsLessonIdRoute: CurriculumLessonsLessonIdRoute,
  LibraryCollectionsIndexRoute: LibraryCollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
